### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ostgardh** [isabellaalstrom/sensor.krisinformation#10]
I get error when I check my config in Hass.

  File "/home/homeassistant/.homeassistant/custom_components/krisinformation/sensor.py", line 71
    name = f"{DEFAULT_NAME} {country}"
                                     ^
SyntaxError: invalid syntax

My config.

  - platform: krisinformation
    name: "Krisinformation Stockholm"
    county: "Västra Götalands län"
    latitude: !secret lat_coord
    longitude: !secret long_coord
    radius: 100

**Comment by isabellaalstrom** [comment]
Are you on the latest version of the component?

**Comment by ostgardh** [comment]
__version__ = '0.0.9'

**Comment by isabellaalstrom** [comment]
I can't seem to recreate this error. How did you install the component?

**Comment by ostgardh** [comment]
Hmm. ok strange.
 I have done
Login as homeassistant
cd .homeassistant
cd custom_components
mkdir krisinformation
cd krisinformation
wget https://raw.githubusercontent.com/isabellaalstrom/sensor.krisinformation/master/custom_components/krisinformation/sensor.py
Add my config to configuration.yaml
restart hass.

But I can test again..
And se if I can find some error

**Comment by isabellaalstrom** [comment]
Are you on the latest version of home assistant as well?

**Comment by ostgardh** [comment]
Home Assistant
0.88.1

**Comment by ostgardh** [comment]
Have update to 0.88.2
Same problem.

**Comment by isabellaalstrom** [comment]
Can you try to make a sensor with just this, no other config

```
- platform: krisinformation

**Comment by isabellaalstrom** [comment]
And maybe one like this:
```
  - platform: krisinformation
    country: 'Sverige'

**Comment by ostgardh** [comment]
I have try to have only - platform: krisinformation
and remove all my config and have only basic config and platform: krisinformation.
No same..

**Comment by ostgardh** [comment]
If I edit row 71 
from:
name = f"{DEFAULT_NAME} {country}"
To:
name = "{DEFAULT_NAME} {country}"

The check on config is ok..

**Comment by isabellaalstrom** [comment]
f-strings was introduced in python 3.6, and it seems that your system can't handle them, which is weird because you should have that?

**Comment by ostgardh** [comment]
Ok.. I run Python 3.5.3

**Comment by isabellaalstrom** [comment]
I can rewrite the line for a future release to be backwards compatible. With your fix the only thing you miss out on is default name on country sensor if you don't specify your own.
