### ISSUE TITLE
Alerts in Swedish

### ISSUE THREAD

**Issue by Davst** [isabellaalstrom/sensor.krisinformation#19]
Is there a flag, or is there a possibility to add a flag to get the output information in swedish?

**Comment by isabellaalstrom** [comment]
What do you mean by output information?

**Comment by Davst** [comment]
Added the sensor. And the current output of it is ”No new messages”. I figured it was tracking the information from krisinformation in English. Is there a Swedish feed as well or is it just the blank output that is in English?

**Comment by isabellaalstrom** [comment]
Ah, no the feed is only in Swedish, but the state is only in English atm. The custom card however shows it in Swedish.

**Comment by Davst** [comment]
Okay that explains it nvm then, I haven't gotten to implementing the card.
