### ISSUE TITLE
Check Home Assistant configuration

### ISSUE THREAD

**Issue by skaker1** [isabellaalstrom/sensor.krisinformation#20]
Hi!

Checking for Home Assistant 0.106.1:

Failed config
  General Errors: 
    - Platform error sensor.krisinformation - No module named 'jsonpath'

**Comment by NateRobinsonS** [comment]
Same here.  Looks like jsonpath used to be part of HA core.

I run from a venv, so `pip install jsonpath` took care of the problem in my case.

**Comment by isabellaalstrom** [comment]
Alright. I'll look into it, but I'm on 106.2 with no problems.
