### ISSUE TITLE
API link not supported any more?

### ISSUE THREAD

**Issue by yabbah** [isabellaalstrom/sensor.krisinformation#25]
Seems like https://api.krisinformation.se/v2/feed?format=json isn't working properly anymore. Give an empty response, so the sensors becomes empty most of the time. 

I'll checked https://api.krisinformation.se/ and it seems like v1 is the only deployed and supported version. I tried change to v1 in the code, but it wont load the component.

**Comment by isabellaalstrom** [comment]
I can see that my sensors are full with up to date information, so I don't know if this is an issue really, or maybe an intermittent one from their end.

**Comment by yabbah** [comment]
You're right. Seems like a intermittent issue from their API.
