### ISSUE TITLE
Error in sensor, implements device_state_attributes

### ISSUE THREAD

**Issue by KentEkl** [isabellaalstrom/sensor.krisinformation#32]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549 
First occurred: 08:09:12 (2 occurrences) 
Last logged: 08:09:13

Entity sensor.krisinformation_sandviken (<class 'custom_components.krisinformation.sensor.KrisinformationSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.krisinformation_sverige (<class 'custom_components.krisinformation.sensor.KrisinformationSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by isabellaalstrom** [comment]
This is on the beta, right?

**Comment by KentEkl** [comment]
Yes, sorry 😞

**Comment by KentEkl** [comment]
The error persists in version 2021.12.0
