### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by AnderssonPeter** [isabellaalstrom/sensor.krisinformation#4]
Hej Tack för en underbar komponent, finns det något sätt att fejka data så jag kan testa om min automation funkar?

**Comment by isabellaalstrom** [comment]
Det enklaste sättet är att gå in i dev_tools, söka rätt på entityn, trycka upp den så den kommer upp så du kan ändra, och ändra till det som triggar din automation och sen spara!

**Comment by AnderssonPeter** [comment]
Jag hade tur igår det bran någonstans i Skåne så fick ett alarm (tur för mig inte för dom) så jag har lyckats testa.
